version: '3.2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "zxcvbnm,"

  # db:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "zxcvbnm,"
  #     MYSQL_DATABASE: hospital
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: "zxcvbnm,"
  #   volumes:
  #     - mysqldata:/var/lib/mysql

  durka:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    environment:
      DB_TYPE: mysql # 'mysql' or 'postgres'
      DB_HOST: db
      DB_NAME: hospital
      DB_USER: user
      DB_PASSWORD: "zxcvbnm,"

# volumes:
#   mysqldata:

